package com.careerpilot.config;

import com.careerpilot.entity.*;
import com.careerpilot.repository.*;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.time.LocalDate;
import java.util.*;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.CommandLineRunner;
import org.springframework.core.io.ClassPathResource;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

/** Loads seed/seed.json (generated by dataset/generate_dataset.py) the first time the database is empty. */
@Slf4j @Component @RequiredArgsConstructor
public class DataSeeder implements CommandLineRunner {
    private final UserRepository userRepo;
    private final StudentRepository studentRepo;
    private final SkillRepository skillRepo;
    private final CompanyRepository companyRepo;
    private final JobRepository jobRepo;
    private final ApplicationRepository appRepo;
    private final PasswordEncoder encoder;
    private final ObjectMapper om;
    @Value("${careerpilot.seed.enabled:true}") private boolean enabled;

    @Override @Transactional
    public void run(String... args) throws Exception {
        if (!enabled || userRepo.count() > 0) return;
        JsonNode root = om.readTree(new ClassPathResource("seed/seed.json").getInputStream());

        Map<String, Skill> skills = new HashMap<>();
        for (JsonNode n : root.get("skills")) skills.put(n.asText().toLowerCase(), skillRepo.save(new Skill(n.asText())));

        User admin = new User();
        admin.setEmail(root.get("admin").get("email").asText());
        admin.setPasswordHash(encoder.encode(root.get("admin").get("password").asText()));
        admin.setRole(Role.ADMIN);
        userRepo.save(admin);

        Map<String, Company> companies = new HashMap<>();
        for (JsonNode n : root.get("companies")) {
            Company c = new Company();
            c.setName(n.get("name").asText()); c.setLocation(n.get("location").asText()); c.setWebsite(n.get("website").asText());
            companies.put(c.getName(), companyRepo.save(c));
        }

        Map<String, Job> jobs = new HashMap<>();
        for (JsonNode n : root.get("jobs")) {
            Job j = new Job();
            j.setCompany(companies.get(n.get("company").asText()));
            j.setTitle(n.get("title").asText()); j.setDescription(n.get("description").asText());
            j.setMinimumCgpa(n.get("minimumCgpa").asDouble()); j.setLocation(n.get("location").asText());
            j.setSalaryLpa(n.get("salaryLpa").asDouble()); j.setJobType(n.get("jobType").asText());
            j.setDeadline(LocalDate.now().plusDays(n.get("deadlineDays").asInt()));
            j.setStatus(n.get("deadlineDays").asInt() < 0 ? JobStatus.CLOSED : JobStatus.OPEN);
            if (!n.get("graduationYear").isNull()) j.setGraduationYear(n.get("graduationYear").asInt());
            j.setAllowedDegrees(n.get("allowedDegrees").asText());
            for (JsonNode s : n.get("skills")) j.getSkills().add(skills.get(s.asText().toLowerCase()));
            jobs.put(n.get("ref").asText(), jobRepo.save(j));
        }

        Map<String, Student> students = new HashMap<>();
        for (JsonNode n : root.get("students")) {
            User u = new User();
            u.setEmail(n.get("email").asText()); u.setRole(Role.STUDENT);
            u.setPasswordHash(encoder.encode(root.get("studentPassword").asText()));
            userRepo.save(u);
            Student s = new Student();
            s.setUser(u); s.setName(n.get("name").asText()); s.setCollege(n.get("college").asText());
            s.setDegree(n.get("degree").asText()); s.setCgpa(n.get("cgpa").asDouble());
            s.setGraduationYear(n.get("graduationYear").asInt()); s.setPhone(n.get("phone").asText());
            s.setProjects(n.get("projects").asText()); s.setCertifications(n.get("certifications").asText());
            for (JsonNode k : n.get("skills")) s.getSkills().add(skills.get(k.asText().toLowerCase()));
            students.put(u.getEmail(), studentRepo.save(s));
        }

        int count = 0;
        for (JsonNode n : root.get("applications")) {
            Application a = new Application();
            a.setStudent(students.get(n.get("student").asText())); a.setJob(jobs.get(n.get("job").asText()));
            a.setStatus(ApplicationStatus.valueOf(n.get("status").asText()));
            a.setAppliedAt(java.time.Instant.now().minus(n.get("daysAgo").asInt(), java.time.temporal.ChronoUnit.DAYS));
            appRepo.save(a); count++;
        }
        log.info("Seeded {} skills, {} companies, {} jobs, {} students, {} applications",
                skills.size(), companies.size(), jobs.size(), students.size(), count);
        log.info("Demo logins -> admin: {} | student: {} (see README for passwords)",
                admin.getEmail(), root.get("students").get(0).get("email").asText());
    }
}
